# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/gotestyourself/gotestyourself";
    fetch = {
      type = "git";
      url = "https://github.com/gotestyourself/gotestyourself";
      rev = "fdfe80720462efcc86ceac8ab7648e50c7c40850";
      sha256 = "19av7z9lzriix2k2xx8g25h6ya0hsx2z0862wqipfzjnmjiky8dd";
    };
  }
  {
    goPackagePath = "github.com/google/go-cmp";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-cmp";
      rev = "3af367b6b30c263d47e8895973edcca9a49cf029";
      sha256 = "1fbv0x27k9sn8svafc0hjwsnckk864lv4yi7bvzrxvmd3d5hskds";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "30136e27e2ac8d167177e8a583aa4c3fea5be833";
      sha256 = "1rl2lw4fgqh01dwh9srbi3r14xnlx9mslcr532zav64rai89fwkb";
    };
  }
  {
    goPackagePath = "github.com/pmezard/go-difflib";
    fetch = {
      type = "git";
      url = "https://github.com/pmezard/go-difflib";
      rev = "792786c7400a136282c1664665ae0a8db921c6c2";
      sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "be8372ae8ec5c6daaed3cc28ebf73c54b737c240";
      sha256 = "1ljfacbhd180yr0lc9myvxxdka0iji2ihsx0fcczja4ik5f2mb5p";
    };
  }
]
