#!@bash@/bin/bash

PATH=@stdenv@/bin:@blur@/bin:@jq@/bin:@grim@/bin:@sway@/bin${PATH:+:}$PATH
export PATH

declare -a sway_outputs
declare -a sway_screenshots
declare -a swaylock_params

while read -r line; do
    sway_outputs+=("$line")
    sway_screenshots+=("$(mktemp --suffix=.jpg)")
done <<< "$(swaymsg -t get_outputs | jq -r .[].name)"

swaylock_params+=("-e" "-K" "-s" "fill" "--font=Roboto" "--inside-color=00000066" "--inside-clear-color=00660099" "--inside-ver-color=00006699" "--inside-wrong-color=66000099" "--key-hl-color=FFFFFF99" "--ring-color=GGGGGGBB" "--ring-wrong-color=FF6666BB" "--ring-ver-color=6666FFBB" "--text-color=FFFFFFFF" "--text-clear-color=FFFFFFFF" "--text-wrong-color=FFFFFFFF" "--text-ver-color=FFFFFFFF" "--indicator-radius=80")

trap 'rm -f "${sway_screenshots[*]}"' EXIT

arraylen=${#sway_outputs[@]}
for (( i=0; i<arraylen; i++ ));
do
    grim -t jpeg -o "${sway_outputs[$i]}" "${sway_screenshots[$i]}"
    blur "${sway_screenshots[$i]}" /tmp/bg-"$i".png
    swaylock_params+=("-i" "${sway_outputs[$i]}:/tmp/bg-$i.png")
done

swaylock "${swaylock_params[@]}"