apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: buildkite-agent-linux
spec:
 serviceName: buildkite-agent-linux
 replicas: 4
 selector:
   matchLabels:
     app: buildkite-agent-linux
 template:
   metadata:
     labels:
       app: buildkite-agent-linux
   spec:
     initContainers:
       - name: buildkite-init
         image: johnae/buildkite-nix
         imagePullPolicy: IfNotPresent
         volumeMounts:
           - name: buildkite
             mountPath: /nixstore
             subPath: nix
         command: [ "bash", "-c" ]
         args: [ "cp -pur /nix/* /nixstore/" ]
     containers:
       - name: dockerd
         image: docker:18.05-dind
         securityContext:
           privileged: true
         volumeMounts:
           - name: buildkite
             subPath: docker
             mountPath: /var/lib/docker
           - name: buildkite
             subPath: nix
             mountPath: /nix
       - name: buildkite-agent
         image: johnae/buildkite-nix
         imagePullPolicy: IfNotPresent
         envFrom:
           - secretRef:
               name: buildkite-agent-env
         env:
           - name: USER
             value: root
           - name: DOCKER_HOST
             value: tcp://localhost:2375
           - name: BUILDKITE_BUILD_PATH
             value: /buildkite/builds
           - name: BUILDKITE_PLUGINS_PATH
             value: /buildkite/plugins
           - name: BUILDKITE_AGENT_TAGS
             value: 'queue=linux,queue=default,nix=true'
           - name: BUILDKITE_AGENT_TAGS_FROM_HOST
             value: 'true'
           - name: LANG
             value: 'en_US.UTF-8'
         volumeMounts:
           - name: ssh-keys
             mountPath: /root/.ssh/id_rsa
             subPath: id_rsa
           - name: buildkite
             subPath: buildkite
             mountPath: /buildkite
           - name: buildkite
             mountPath: /nix
             subPath: nix
     volumes:
       - name: ssh-keys
         secret:
           secretName: buildkite-agent-ssh
           defaultMode: 0400
 volumeClaimTemplates:
   - metadata:
       name: buildkite
     spec:
       accessModes: [ "ReadWriteOnce" ]
       resources:
         requests:
           storage: 30Gi