apiVersion: apps/v1
kind: Deployment
metadata:
  name: btrfs-backups
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btrfs-backups
  template:
    metadata:
      labels:
        app: btrfs-backups
    spec:
      containers:
        - name: btrfs-backups
          image: johnae/btrfs-backups
          imagePullPolicy: IfNotPresent
          ports:
          - name: ssh
            containerPort: 22
            protocol: TCP
          securityContext:
            privileged: true
          readinessProbe:
            tcpSocket:
              port: ssh
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: ssh
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
          - name: storage-volume
            mountPath: /storage
      volumes:
      - name: storage-volume
        hostPath:
          path: /mnt/backup/@backups
      nodeSelector:
        kubernetes.io/hostname: titan