apiVersion: v1
kind: Service
metadata:
  name: btrfs-backups
  labels:
    app: btrfs-backups
  annotations:
    metallb.universe.tf/allow-shared-ip: sshserv
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.240.241
  ports:
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app: btrfs-backups